grpc:
  address: ":50051"

haproxy:
  instance_name: "lbm-default"
  configuration_file: "/etc/haproxy/haproxy.cfg"
  socket:
    network: "unix"
    address: "/var/run/haproxy/master.sock"
    timeout: "3s"
  managed_configurations_store:
    backend: "memory"
    redis:
      address: ""
      username: ""
      password: ""
      db: 0
